spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.168.1.150:3306/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: test1234
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 5

mybatis:
  type-aliases-package: com.choway.springboot.tk.mybatis.model
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
  identity: MYSQL
  not-empty: true
  style: camelhump
  enable-method-annotation: true
  safe-delete: true
  safe-update: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
