spring:
  application:
    name: cache-redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.168.1.150:3306/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: test1234
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  redis:
    database: 0
    host: 172.168.1.150
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

server:
  port: 8080
